import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Typography } from "@mui/material";
import BulkRefresh from "../components/BulkRefresh";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bulk Metadata Refresh on OpenSea</h1>

        <p className={styles.description}>
          Get started by entering some token IDs
        </p>
        <BulkRefresh />
      </main>

      <footer className={styles.footer}>
        <Typography>
          This tool uses the OpenSea public API. Use this tool at your own
          discretion, it was created in an hr as a side project by{" "}
          <span>
            <a href="https://twitter.com/AspynPalatnick">Aspyn</a>
          </span>
        </Typography>
      </footer>
    </div>
  );
};

export default Home;
